stages:
  - validate
  - build

syntax_check:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.1.0
  tags: [linux, docker]
  script:
    - find . -type f -iregex ".*\.\(c\|h\|cpp\|ino\)" -exec clang-format-6.0 -i -style=file {} \; && git diff --exit-code


cppcheck:
  stage: validate
  image:
      name: registry.gitlab.sensirion.lokal/mso-sw/drivers/docker-driver-generator:0.1.0
  tags: [linux, docker]
  script:
    - cppcheck --std=c89 --language=c --error-exitcode=1 --enable=warning,style,performance,portability -i sample-implementations/ .

build:
  stage: build
  image:
    name: sensirion/embedded-ci:2.3.0
  tags: [linux, docker]
  script:
    - make
